### ISSUE TITLE
Pencil sketch using OpenCV

### ISSUE THREAD

**Issue by mansi75** [geekquad/Pixel-Processing#302]
Pencil sketch on images using openCV. Kindly, assign me this.

**Comment by PritKalariya** [comment]
I'd like to work on this issue (Pencil Sketch on images using OpenCV).

Please assign me.

**Comment by geekquad** [comment]
> I'd like to work on this issue (Pencil Sketch on images using OpenCV).
> 
> Please assign me.

Hey @PritKalariya,
We are focusing more on the implementation of the technique and not on its application. Feel free to raise an issue if you have something in mind. Thank you.
