### ISSUE TITLE
Watershed Algorithm.

### ISSUE THREAD

**Issue by Ayush12062000** [geekquad/Pixel-Processing#73]
Hello, I am Ayush Kesarwani, GSSoC`21 participant, and want to contribute to the Implementation of Image Segmentation with Watershed Algorithm.

Kindly, assign this issue to me.
@geekquad @kritikaparmar-programmer

**Comment by geekquad** [comment]
Assigning you with the same @Ayush12062000.

**Comment by NikkiPriya** [comment]
I have already made changes in my machine can you please assign it to me so that I can commit it?
